name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        uses: boardgamesesh/app/.github/workflows/pnpm-install.yml

      - name: Lint
        run: pnpm lint
